### ISSUE TITLE
Can I able to get the trees before embedded?

### ISSUE THREAD

**Issue by Clarit7** [evelinehong/LBF#3]
Hi, I read your paper and it was very impressive. Thanks for publishing cool research and implementation.
The code seems working well, but I'm struggling in a small problem.
Can I get trees before embedded? I checked several variables and most of them was embedded information which is non-interpretable. I want visualized trees or readable mathematical expressions in training or testing steps.
It will be glad to receive an answer :)

**Comment by evelinehong** [comment]
Can you be more specific?
What do you mean by "embedded"?

**Comment by Clarit7** [comment]
> Can you be more specific?
> What do you mean by "embedded"?

I mean, interpretable or visualized trees which is readable. Not tensorized informations.
Most of variables have value of encoded informations like tensor([-1.202, 0.134, 2.210, ...]) so that human can't understand.
I wonder which object is the reasoning tree or the solution tree, containing true values of operators and constants like Node(value : '+', leftchild : '123', rightchild : '*').
Sorry for pool English descriptions. I'm not native speaker. Maybe it would be better to use 'encoded' rather than 'embedded'.

**Comment by evelinehong** [comment]
Hi,

For the trees in the testing phase, please see Line 170 in the run_seq2tree.py script. The test_exp should be what you want.

For training phase, if you want the tree before fixing, please see Line 359 in src/train_and_evaluate.py. If you want the tree after fixing, please see Line 376- Line 377 in src/train_and_evaluate.py.

If you plan to get the symbols in the fixing phase, I think it's something like "tok.symbol for tok in self.tokens" in src/diagnosis_multistep.py.

(Note that prefix expressions, trees and infix expressions are interchangeable)

**Comment by Clarit7** [comment]
Thanks for the detailed explanation. :)
I'll try it as you told.

**Comment by evelinehong** [comment]
solved
