### ISSUE TITLE
The model in github is well-training?

### ISSUE THREAD

**Issue by SCUTykLin** [evelinehong/LBF#5]
Does the models (models/generator, merge,....) you provided is well-training？Can I use it to test directly?

**Comment by SCUTykLin** [comment]
souse like the model you provided in github did not train, I try and got 0.3%accurary.

**Comment by evelinehong** [comment]
> Does the models (models/generator, merge,....) you provided is well-training？Can I use it to test directly?

Currently we do not provide checkpoints.
