### ISSUE TITLE
[Solved] Question about the best test accuracy？Difference of the paper

### ISSUE THREAD

**Issue by SCUTykLin** [evelinehong/LBF#6]
I ran the model (100 epoch, 50-fix, ma-fix) and got 53.2%. According to the paper, the setting the same as mine is 59.4% (the heighest accracy of the test is 100-fix, 59.6%). Does additive condition existed for 59.4%? I just 53.2%
The setting in your code is 
![image](https://user-images.githubusercontent.com/34080744/128481836-16cf5d56-365f-4af9-a864-e6d518c3069d.png)
I did not change.

**Comment by SCUTykLin** [comment]
Or you could provide the checkpoint

**Comment by evelinehong** [comment]
Hi,
I will update the codes soon, and will let you know here once i update the codes.

**Comment by evelinehong** [comment]
Also, initialization may result in the difference of the performances.

**Comment by evelinehong** [comment]
Hi,

I found the bug. Just comment these two lines:
https://github.com/evelinehong/LBF/blob/77f2d381c2e1884fdb239f77d8b6ed1ca407d701/src/train_and_evaluate.py#L379-L380
It seems that there's sth wrong with the eval function.

And the codes can get similar results to the paper (with probably a 1% variance).

Sorry for the inconvenience!

Best,
Yining

**Comment by evelinehong** [comment]
I will temporarily close this issue. Feel free to open new ones if you have further questions,

**Comment by SCUTykLin** [comment]
你们这里还有一个问题，你们的answer是通过eval(answer[idx])得到答案的，答案包含了%或者不规范你们是解不出来的，比如40%, 5((1)/(2))这种，会报错，然后你全部try catch掉了，这部分占了687个，你们为什么不处理这部分问题？还是说觉得解决了没有贡献之类的？

**Comment by evelinehong** [comment]
Thanks for pointing it out! We really appreciate it that you look so carefully into the codes! 

I think cases like 5((1)/(2)) are tackled here: 
https://github.com/evelinehong/LBF/blob/77f2d381c2e1884fdb239f77d8b6ed1ca407d701/src/pre_data.py#L291-L293
However, in the data processing codes, the "%" cases seem not to be handled.

I guess if we handle them all, we can still improve the results.
However, I'm super busy right now, and I cannot quite remember everything I wrote two years ago. So I might be a little slow to update the codes. Give me some time!

Again, thanks for your suggestions! xiexie!

**Comment by SCUTykLin** [comment]
还有一个小小的请求，可以把你训练好的模型上传上来吗，我不想跑了，谢谢

**Comment by evelinehong** [comment]
Sure I'll upload the model when I have the final version.

Are you in a rush for any conference deadline?

**Comment by SCUTykLin** [comment]
no, anytime

**Comment by SCUTykLin** [comment]
姐我觉得答案5((1)/(2))这种问题你好像处理过了，主要是答案包含了%的问题，在train_and_evaluate.py的find_fix61行，gt = eval(gt)，你只需要替换成gt = eval(replace("%", 100))就好了

**Comment by SCUTykLin** [comment]
你之前那个bug的原因就是%号，比如equation = 10 * 20%，你在find_fix里变成了10* (0.2)，结果fix传回来的时候又变回10 * 20%，也就是eval(fix_infix)那里，eval识别不了%就报错了，而你又把错误忽略了。

**Comment by evelinehong** [comment]
是的我修改了这些地方

https://github.com/evelinehong/LBF/blob/ef03dd9c9eb2c358832c204b2e3ac2e3dea1e0a6/src/pre_data.py#L291-L299

**Comment by SCUTykLin** [comment]
打扰了姐，不知道是不是我打开方式不对
![image](https://user-images.githubusercontent.com/34080744/131288493-15060e83-f942-4430-9438-faa19883ff3e.png)
我只能到54.2%，准确率在90epoch的时候就趋于稳定
参数如下，是你文章初始化的：
![image](https://user-images.githubusercontent.com/34080744/131288644-cae34e1a-06e4-426d-bdb4-61bc77e8d6c1.png)
我可以使用我跑出来的准确率吗？

**Comment by GreenArrow2017** [comment]
其实我觉得差点也无所谓，你是第一篇做MWP半监督的，能有54已经很好了

**Comment by evelinehong** [comment]
你用的是最新代码么？不可能。我现在46epoch就58.7%准确率了。
你用的是我最后一次commit之后的代码么？

**Comment by SCUTykLin** [comment]
那我再试一下

**Comment by SCUTykLin** [comment]
那可以先上传一下准确率最高的那个模型吗？可能是我代码问题 我再跑一遍

**Comment by evelinehong** [comment]
稍等，我checkpoint有点乱，可能需要找一下。这个是我跑的结果
![log](https://user-images.githubusercontent.com/32010547/131291328-bf127755-ae1c-4ec0-a8c3-ae392a12db59.png)

**Comment by SCUTykLin** [comment]
我其实只是想要一个模型做一两个测试而已。。。。

**Comment by evelinehong** [comment]
https://drive.google.com/drive/folders/1-BHCZrB_oLt-vgqjI6gI7YdOU68YAZ-X?usp=sharing
chekpoint 在这里

**Comment by evelinehong** [comment]
我在跑一个新的，有更好的结果放上来

**Comment by SCUTykLin** [comment]
好  谢谢

**Comment by evelinehong** [comment]
方便问下你是用哪个version么？改动了哪些地方？除了最开始那个应该都不会有54%的准确率。。
以及你是想拿这个做baseline么？

**Comment by SCUTykLin** [comment]
就是直接clone github上面最新的呀  是想做baseline

**Comment by evelinehong** [comment]
QAQ那怎么做到十几个小时跑100个epoch的。。。

**Comment by SCUTykLin** [comment]
跑两天  28号你修改的那个模型开始跑，我跑一个epoch要15分钟  大佬你要半个小时

**Comment by SCUTykLin** [comment]
其实我也不确定是不是我机器问题  为什么会和你训练时间相差那么久

**Comment by SCUTykLin** [comment]
![image](https://user-images.githubusercontent.com/34080744/131295113-7ccababb-3ff9-41f4-af20-73851c878bcc.png)
15分钟一个epoch

**Comment by evelinehong** [comment]
感觉确实是，如果15分钟的话，那说明memory buffer里的fix不够多，准确率就肯定不够高。

我再多跑几个模型。看有没有你说的问题。辛苦了。

**Comment by SCUTykLin** [comment]
我确实是用了28号姐你修改的那个模型，之前bug的model没有fix的problem有3200-3300个，28号你修了第一个bug后只有730个左右了，除去带有%问题的640个problem，就只有90个左右的problem是无法溯因推理出fix的，然后你昨天又把那个640个带有%的problem处理了，也就是第二个bug。
我跑的是你修改了第一个bug的model

**Comment by evelinehong** [comment]
嗯嗯我昨天这个时候upload了一个新的模型，准确率应该比两天前那个更高。
但两天前那个也至少应该有57-58%的准确率。（我可以上传我两天前跑的模型）

你可以先用checkpoint evaluate一下。我如果有更好的checkpoint再上传。
辛苦你了。跑baseline跑了那么久。

**Comment by SCUTykLin** [comment]
没事，谢谢解答了，打扰您这么长时间，祝科研有成，一夜暴富

**Comment by SCUTykLin** [comment]
跑出来了，结果没问题，50 nstep就能到59.7%，打扰了

**Comment by evelinehong** [comment]
嗯嗯，我update了一个59.8%的checkpoint

**Comment by SCUTykLin** [comment]
老板那个问一下，这个GTS的evaluate里面，有没有batch的beam search的版本呀，我看你做的beam search是单条样本的
